version: '3.7'

services:
  # Spring Boot application docker image
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db # This service depends on mysql to start first.
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dentistdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: dentistuser
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - backend

# database docker image
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: dentistdb
      MYSQL_USER: dentistuser
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/mysql
      - ${PWD}/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - backend

# Volume config
volumes:
  db-data:

# Networks config
networks:
  backend: